= Visual Embed SDK Reference 
:toc: true

:page-title: Visual Embed SDK Reference
:page-pageid: js-reference
:page-description: Visual Embed SDK Reference

The ThoughtSpot Visual Embed SDK is a Javascript library used for embedding ThoughtSpot visualizations, pinboards, and the entire application in web applications. The Embed SDK library allows you to connect your applications to the ThoughtSpot embedded components and programmatically import them within your application framework.

== Visual Embed SDK libraries
The link:/typedoc/index.html[Visual Embed SDK] is available for download as `@thoughtspot/embed-sdk` through link:https://www.npmjs.com/package/@thoughtspot/embed-sdk[NPM, window=_blank] includes the following packages:

* `SearchEmbed`
* `PinboardEmbed`
* `AppEmbed`
 
For more specific information on Embed options and functions, visit our link:https://docs.thoughtspot.com/visual-embed-sdk/typedoc/modules.html[API site, window=_blank].

== Functions
* link:/typedoc/modules.html[Init]

== Additional resources
 
For information on how to use the Visual Embed SDK, see xref:getting-started.adoc[Get Started].